# Generated by Django 5.2 on 2025-04-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdesenvolvimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqdesenvolvimento',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
