# Generated by Django 5.2 on 2025-04-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.TextField()),
                ('operacao_agricola', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('cadeia_produtiva', models.CharField(max_length=100)),
                ('codigo_produto', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('foto', models.CharField(max_length=100)),
                ('link_pagina', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
            ],
        ),
    ]
