# Generated by Django 5.2 on 2025-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='hp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='operacao_agricola',
            field=models.CharField(),
        ),
    ]
