# Generated by Django 5.2 on 2025-04-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0008_maquina_codigo_finame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='cadeia_produtiva',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='codigo_finame',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='codigo_produto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='hp',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='link_pagina',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='operacao_agricola',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
