# Generated by Django 5.2 on 2025-04-14 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0009_alter_maquina_cadeia_produtiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='cadeia_produtiva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='codigo_finame',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='codigo_produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='data_registro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='hp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='link_pagina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='operacao_agricola',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
