# Generated by Django 5.2 on 2025-04-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0011_maquina_cnpj_fabricante_maquina_cultura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(choices=[('TRATOR', 'Trator'), ('IMPLEMENTO AGRÍCOLA', 'Implemento Agrícola')], default='', max_length=100, null=True),
        ),
    ]
