# Generated by Django 5.2 on 2025-04-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0002_alter_maquina_categoria_alter_maquina_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(choices=[('TRATOR', 'Trator'), ('IMPLEMENTO AGRÍCOLA', 'Implemento Agrícola')], default='', max_length=100),
        ),
    ]
