# Generated by Django 5.2 on 2025-04-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0004_alter_maquina_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
