# Generated by Django 5.2 on 2025-04-08 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0005_maquina_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='data_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
