# Generated by Django 5.2 on 2025-04-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0007_alter_maquina_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='codigo_finame',
            field=models.CharField(default='', max_length=100),
        ),
    ]
