# Generated by Django 5.2 on 2025-04-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0010_alter_maquina_cadeia_produtiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='cnpj_fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='cultura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='etapa',
            field=models.CharField(choices=[('PLANTIO', 'Plantio'), ('PREPARO DE SOLO', 'Preparo de Solo'), ('COLHEITA', 'Colheita'), ('PLANTIO', 'Plantio'), ('PÓS-COLHEITA', 'Pós-Colheita')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='maquina',
            name='funcao',
            field=models.CharField(choices=[('PRODUTIVA', 'Produtiva')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='maquina',
            name='linha_financiamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='natureza',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='ncm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='ncm_descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='nome_fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tema',
            field=models.CharField(choices=[('GRÃOES E FORRAGENS', 'Grãos e Forragens'), ('HORTICULTURA', 'Horticultura'), ('FRUTÍFERAS', 'Frutíferas'), ('TODAS', 'Todas'), ('OUTROS', 'Outros')], default='', max_length=100),
        ),
    ]
