# Generated by Django 5.2 on 2025-04-30 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0012_alter_maquina_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='data_registro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='etapa',
            field=models.CharField(choices=[('PLANTIO', 'Plantio'), ('PREPARO DE SOLO', 'Preparo de Solo'), ('COLHEITA', 'Colheita'), ('PLANTIO', 'Plantio'), ('PÓS-COLHEITA', 'Pós-Colheita')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='funcao',
            field=models.CharField(choices=[('PRODUTIVA', 'Produtiva')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='publicada',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tema',
            field=models.CharField(choices=[('GRÃOES E FORRAGENS', 'Grãos e Forragens'), ('HORTICULTURA', 'Horticultura'), ('FRUTÍFERAS', 'Frutíferas'), ('TODAS', 'Todas'), ('OUTROS', 'Outros')], default='', max_length=100, null=True),
        ),
    ]
