# Generated by Django 5.2 on 2025-07-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0013_alter_maquina_data_registro_alter_maquina_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='ano_aquisicao_item',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='aspectos_item_boas_praticas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='capacitacao_manutencao_item',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='caracteristicas_detalhadas_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='condicoes_adequadas_uso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='faz_manutencao_item',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='frequencia_manutencao_item_12_meses',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='frequencia_uso_item',
            field=models.CharField(choices=[('ESPORÁDICA', 'Esporádica'), ('DIÁRIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='impacto_positivo_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='insumos_item',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='item_gera_residuo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='local_aquisicao_item',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='problema_item_12_meses',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='produto_linha_producao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='qual_residuo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tempo_uso_item_mes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo_uso_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='utilizacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='etapa',
            field=models.CharField(choices=[('PLANTIO', 'Plantio'), ('PREPARO DE SOLO', 'Preparo de Solo'), ('COLHEITA', 'Colheita'), ('PÓS-COLHEITA', 'Pós-Colheita')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='natureza',
            field=models.TextField(blank=True, choices=[('TRATORES', 'Tratores'), ('PULVERIZADOR_AGRICOLA', 'Pulverizador Agrícola'), ('MÁQUINAS E APARELHOS PARA PREPARAÇÃO, TRABALHO DO SOLO OU CULTURA', 'Máquinas e aparelhos para preparação, trabalho do solo ou cultura')], null=True),
        ),
    ]
