# Generated by Django 5.2 on 2025-07-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0014_maquina_ano_aquisicao_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='capacidade_producao_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='codigo_catalogo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='codigo_questionario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='estimativa_da_demanda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='n',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='sub_etapa_atividade',
            field=models.CharField(choices=[('PLANTIO', 'Plantio'), ('PREPARO DE SOLO', 'Preparo de Solo'), ('COLHEITA', 'Colheita'), ('PÓS-COLHEITA', 'Pós-Colheita')], default='', max_length=100, null=True),
        ),
    ]
