# Generated by Django 5.2 on 2025-07-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0015_maquina_capacidade_producao_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='n',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
