# Generated by Django 5.2 on 2025-07-15 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_alter_fornecedor_cnpj'),
        ('maqdisponivel', '0016_alter_maquina_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedor', to='fornecedores.fornecedor'),
        ),
    ]
