# Generated by Django 5.2 on 2025-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0017_maquina_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='tema',
            field=models.CharField(choices=[('FRUTIFERAS', 'Frutíferas'), ('GRÃOES E FORRAGENS', 'Grãos e Forragens'), ('HORTICULTURA', 'Horticultura'), ('SOCIOBIODIVERSIDADE', 'Sociobiodiversidade'), ('TODAS', 'Todas'), ('OUTROS', 'Outros')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(choices=[('EQUIPAMENTO', 'Equipamento'), ('FERRAMENTA', 'Ferramenta'), ('INSTRUMENTO', 'Instrumento'), ('MAQUINA', 'Máquina'), ('VEICULO', 'Veículo')], default='', max_length=100, null=True),
        ),
    ]
