# Generated by Django 5.2 on 2025-07-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0018_alter_maquina_tema_alter_maquina_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='preco_max_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='preco_min_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ano_aquisicao_item',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='etapa',
            field=models.CharField(choices=[('MANEJO', 'Manejo'), ('MANEJO-INDUSTRIALIZAÇÃO', 'Manejo-Industrialização'), ('PLANTIO', 'Plantio'), ('PREPARO DE SOLO', 'Preparo de Solo'), ('COLHEITA', 'Colheita'), ('PÓS-COLHEITA', 'Pós-Colheita'), ('INDUSTRIALIZAÇÃO', 'Industrialização')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='funcao',
            field=models.CharField(choices=[('CONTROLE DE QUALIDADE', 'Controle de Qualidade'), ('PRODUTIVA', 'Produtiva'), ('TRATAMENTO DE RESIDUOS', 'Tratamento de Resíduos'), ('SEGURANCA E SAUDE DO TRABALHADOR', 'Segurança e Saúde do Trabalhador')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='sub_etapa_atividade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
