# Generated by Django 5.2 on 2025-07-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqdisponivel', '0019_maquina_preco_max_item_maquina_preco_min_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='qts_pessoas_usam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='insumos_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='qual_residuo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
